[workspace]
members = ["core", "fmt", "precompile"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[workspace.dependencies]
jstd = { version = "0.1.0", path = "../../jstd/jstd" }
pcode-types = { version = "0.1.0", path = "../../wazabin-pcode/pcode-types" }
pest = "2.8.6"
pest_derive = "2.8.6"
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
toml = "1"
criterion = "0.8"
sleigh = { version = "0.1.0", path = "core" }
