//! SLEIGH preprocessor: directive handling and macro expansion.
//!
//! [`Preprocessor`] performs a single linear pass over the source files,
//! resolving `@include`, `@define`/`@undef`, and `@if`/`@ifdef`/`@ifndef`/
//! `@elif`/`@else`/`@endif` directives.  The result is a flat text buffer
//! ready for the Pest parser, plus a [`LineMapping`] table so that parse
//! errors can be mapped back to original source locations.

use std::{
    collections::HashMap,
    path::{Path, PathBuf},
};

use crate::diagnostic::{Diagnostic, DiagnosticCode};
use jstd::registry::Registry;

use super::{
    BytePos, FileId, FormatChunk, FormatChunkKind, FormatLine, FormatLineKind, IncludeEdge,
    LineMapping, MacroDefinition, MacroDefinitionId, MacroExpansion, MacroExpansionId,
    PreprocessOptions, SourceDb, SourceMapSegment, SourceOrigin, Span, include_path_span,
};

/// Conditional-compilation stack frame for `@if`/`@ifdef`/`@else`/`@elif`/`@endif`.
#[derive(Clone)]
pub(super) struct IfFrame {
    /// Whether the current branch is being emitted.
    pub(super) active: bool,
    /// Whether any branch of this conditional has been taken.
    pub(super) seen_true: bool,
    /// Span of the opening `@if`/`@ifdef`/`@ifndef` directive.
    pub(super) opened_at: Option<Span>,
}

/// Single-pass preprocessor that resolves directives and flattens includes.
///
/// Constructed by [`super::SourceDb::preprocess`]; field values are moved out
/// after `preprocess_file` returns.
pub(super) struct Preprocessor<'db> {
    pub(super) db: &'db mut SourceDb,
    /// `$(NAME)` macro substitutions active in this preprocessing run.
    defines: HashMap<String, ActiveMacro>,
    /// Flattened output text; one newline appended per non-directive source line.
    pub(super) output: String,
    /// Maps each output line (1-based) back to its original file and line.
    pub(super) line_map: Vec<LineMapping>,
    /// Maps generated byte ranges back to original source byte ranges.
    pub(super) source_map: Vec<SourceMapSegment>,
    /// Lossless physical-line records used by identity formatting.
    pub(super) format_lines: Vec<FormatLine>,
    /// Include edges collected for IDE "go to included file" features.
    pub(super) include_edges: Vec<IncludeEdge>,
    /// Spans of source lines that were skipped by inactive conditionals.
    pub(super) inactive_ranges: Vec<Span>,
    /// Macro definitions seen during preprocessing.
    pub(super) macro_definitions: Registry<MacroDefinitionId, MacroDefinition>,
    /// Macro substitutions emitted into the generated buffer.
    pub(super) macro_expansions: Registry<MacroExpansionId, MacroExpansion>,
    /// Include stack used for cycle detection.
    stack: Vec<FileId>,
    /// Diagnostics accumulated during the run; non-empty ⇒ preprocessing failed.
    pub(super) diagnostics: Vec<Diagnostic>,
}

#[derive(Clone)]
struct ActiveMacro {
    value: String,
    definition: Option<Span>,
    definition_id: Option<MacroDefinitionId>,
}

#[derive(Default)]
struct ExpandedLine {
    text: String,
    chunks: Vec<FormatChunk>,
}

struct PhysicalLine<'a> {
    line_no: usize,
    start: usize,
    end: usize,
    text_without_ending: &'a str,
    text_with_ending: &'a str,
}

impl<'db> Preprocessor<'db> {
    /// Creates a preprocessor seeded with the caller-supplied define set.
    pub(super) fn new(db: &'db mut SourceDb, options: &PreprocessOptions) -> Self {
        Self {
            db,
            defines: options
                .defines
                .iter()
                .map(|(name, value)| {
                    (
                        name.clone(),
                        ActiveMacro {
                            value: value.clone(),
                            definition: None,
                            definition_id: None,
                        },
                    )
                })
                .collect(),
            output: String::new(),
            line_map: Vec::new(),
            source_map: Vec::new(),
            format_lines: Vec::new(),
            include_edges: Vec::new(),
            inactive_ranges: Vec::new(),
            macro_definitions: Registry::default(),
            macro_expansions: Registry::default(),
            stack: Vec::new(),
            diagnostics: Vec::new(),
        }
    }

    fn detect_include_cycle(&self, file: FileId) -> Option<Diagnostic> {
        let cycle_start = self.stack.iter().position(|&id| id == file)?;
        let repeated_from = *self.stack.last()?;

        let mut labels = Vec::new();

        if cycle_start > 0 {
            let first_from = self.stack[cycle_start - 1];
            if let Some(span) = self.include_edge_span(first_from, file) {
                labels.push(crate::DiagnosticLabel {
                    span,
                    message: "cycle starts with this include".to_owned(),
                });
            }
        }

        for pair in self.stack[cycle_start..].windows(2) {
            if let [from, to] = pair
                && let Some(span) = self.include_edge_span(*from, *to)
            {
                labels.push(crate::DiagnosticLabel {
                    span,
                    message: "then includes this file".to_owned(),
                });
            }
        }

        let primary = self
            .include_edge_span(repeated_from, file)
            .or_else(|| self.db.line_span(repeated_from, 1))
            .or_else(|| self.db.line_span(file, 1))
            .unwrap_or_else(|| Span::file_level(file));
        let mut diagnostic = Diagnostic::error(
            DiagnosticCode::Preprocess,
            "include cycle detected",
            primary,
        );

        diagnostic.labels = labels;
        Some(diagnostic)
    }

    /// Evaluates a `@if`/`@elif` condition, reporting a malformed one.
    ///
    /// An unevaluable condition is treated as false so that preprocessing can
    /// continue and report further problems, but it is no longer silent: a
    /// mis-parsed condition used to skip its whole block with no indication
    /// that anything had gone wrong.
    fn eval_condition(&mut self, expr: &str, file: FileId, line_no: usize) -> bool {
        match eval_expr(expr.trim(), &self.defines_as_values()) {
            Ok(cond) => cond,
            Err(error) => {
                self.diagnostics.push(Diagnostic::error(
                    DiagnosticCode::Preprocess,
                    format!(
                        "cannot evaluate condition \"{}\": {}",
                        expr.trim(),
                        error.message
                    ),
                    self.db
                        .line_span(file, line_no)
                        .unwrap_or_else(|| Span::file_level(file)),
                ));
                false
            }
        }
    }

    fn include_edge_span(&self, from: FileId, to: FileId) -> Option<Span> {
        self.include_edges
            .iter()
            .rfind(|edge| edge.from == from && edge.to == to)
            .map(|edge| edge.span)
    }

    /// Recursively preprocesses `file`, appending its output to `self.output`.
    pub(super) fn preprocess_file(&mut self, file: FileId) {
        if let Some(diagnostic) = self.detect_include_cycle(file) {
            self.diagnostics.push(diagnostic);
            return;
        }

        let Some((path, text)) = self
            .db
            .file(file)
            .map(|(path, text)| (path.to_path_buf(), text.to_owned()))
        else {
            self.diagnostics.push(Diagnostic::error(
                DiagnosticCode::Preprocess,
                format!("unknown source file {file}"),
                Span::file_level(file),
            ));
            return;
        };

        self.stack.push(file);

        let mut conditionals: Vec<IfFrame> = Vec::new();

        let physical_lines = physical_lines(&text);
        if physical_lines.is_empty() {
            self.push_format_line(
                file,
                1,
                0,
                0,
                "",
                FormatLineKind::ActiveSource,
                None,
                Vec::new(),
            );
        }

        for physical in physical_lines {
            let line_no = physical.line_no;
            let line = physical.text_without_ending;

            let directive = parse_directive(line);

            let cf_directive = matches!(
                directive,
                Some(
                    Directive::If(_)
                        | Directive::Ifdef(_)
                        | Directive::Ifndef(_)
                        | Directive::Else
                        | Directive::Elif(_)
                        | Directive::Endif
                )
            );
            let parent_active = conditionals.iter().all(|frame| frame.active);

            if !parent_active && !cf_directive {
                if let Some(span) = self.db.line_span(file, line_no) {
                    self.inactive_ranges.push(span);
                }
                self.push_format_line(
                    file,
                    line_no,
                    physical.start,
                    physical.end,
                    physical.text_with_ending,
                    FormatLineKind::InactiveBranch,
                    None,
                    Vec::new(),
                );
                continue;
            }

            self.handle_line(
                file,
                line_no,
                physical.start,
                physical.end,
                line,
                physical.text_with_ending,
                directive,
                path.as_path(),
                &mut conditionals,
            );
        }

        for frame in conditionals {
            let span = frame.opened_at.unwrap_or_else(|| Span::file_level(file));
            self.diagnostics.push(Diagnostic::error(
                DiagnosticCode::Preprocess,
                "unclosed conditional block: missing @endif",
                span,
            ));
        }

        self.stack.pop();
    }

    #[allow(clippy::too_many_arguments)]
    fn handle_line(
        &mut self,
        file: FileId,
        line_no: usize,
        line_start: usize,
        line_end: usize,
        line: &str,
        line_with_ending: &str,
        directive: Option<Directive>,
        path: &Path,
        conditionals: &mut Vec<IfFrame>,
    ) {
        match directive {
            Some(Directive::Include(include)) => {
                let include_span = include_path_span(self.db, file, line_no, line, include);
                let child_path = get_path_from_include(path, include);
                let child = match self
                    .db
                    .file_by_path(&child_path)
                    .map(Ok)
                    .unwrap_or_else(|| self.db.add_file_from_path(&child_path))
                {
                    Ok(child) => child,
                    Err(error) => {
                        let span = include_span.unwrap_or_else(|| Span::file_level(file));
                        self.diagnostics.push(Diagnostic::error(
                            DiagnosticCode::Preprocess,
                            format!("missing include '{}': {error}", child_path.display()),
                            span,
                        ));
                        return;
                    }
                };

                if let Some(span) = include_span {
                    self.include_edges.push(IncludeEdge {
                        from: file,
                        to: child,
                        span,
                    });
                }

                self.preprocess_file(child);
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            Some(Directive::Define(rest)) => {
                if let Some((name, value)) = parse_define(rest) {
                    let definition = self.db.line_span(file, line_no);
                    let definition_id = definition.map(|span| {
                        self.macro_definitions.push(MacroDefinition {
                            name: name.to_owned(),
                            value: value.to_owned(),
                            span,
                        })
                    });
                    self.defines.insert(
                        name.to_owned(),
                        ActiveMacro {
                            value: value.to_owned(),
                            definition,
                            definition_id,
                        },
                    );
                } else {
                    self.diagnostics.push(Diagnostic::error(
                        DiagnosticCode::Preprocess,
                        "@define is missing a definition",
                        self.db
                            .line_span(file, line_no)
                            .unwrap_or_else(|| Span::file_level(file)),
                    ));
                }
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            Some(Directive::Undef(name)) => {
                self.defines.remove(name.trim());
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            Some(Directive::Ifdef(name)) => {
                let cond = self.defines.contains_key(name.trim());
                conditionals.push(IfFrame {
                    active: cond,
                    seen_true: cond,
                    opened_at: self.db.line_span(file, line_no),
                });
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            Some(Directive::Ifndef(name)) => {
                let cond = !self.defines.contains_key(name.trim());
                conditionals.push(IfFrame {
                    active: cond,
                    seen_true: cond,
                    opened_at: self.db.line_span(file, line_no),
                });
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            Some(Directive::If(expr)) => {
                let cond = self.eval_condition(expr, file, line_no);
                conditionals.push(IfFrame {
                    active: cond,
                    seen_true: cond,
                    opened_at: self.db.line_span(file, line_no),
                });
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            Some(Directive::Elif(expr)) => {
                if let Some(frame) = conditionals.last_mut() {
                    if frame.seen_true {
                        frame.active = false;
                    } else {
                        let cond = self.eval_condition(expr, file, line_no);
                        frame.active = cond;
                        frame.seen_true = cond;
                    }
                } else {
                    self.diagnostics.push(Diagnostic::error(
                        DiagnosticCode::Preprocess,
                        "found @elif without matching @if",
                        self.db
                            .line_span(file, line_no)
                            .unwrap_or_else(|| Span::file_level(file)),
                    ));
                }
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            Some(Directive::Else) => {
                if let Some(frame) = conditionals.last_mut() {
                    frame.active = !frame.seen_true;
                    frame.seen_true = true;
                } else {
                    self.diagnostics.push(Diagnostic::error(
                        DiagnosticCode::Preprocess,
                        "found @else without matching @if",
                        self.db
                            .line_span(file, line_no)
                            .unwrap_or_else(|| Span::file_level(file)),
                    ));
                };
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            Some(Directive::Endif) => {
                if conditionals.pop().is_none() {
                    self.diagnostics.push(Diagnostic::error(
                        DiagnosticCode::Preprocess,
                        "found @endif without matching @if",
                        self.db
                            .line_span(file, line_no)
                            .unwrap_or_else(|| Span::file_level(file)),
                    ));
                }
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::Directive,
                    None,
                    Vec::new(),
                );
            }

            None => {
                let generated_start = self.output.len();
                let expanded = self.expand_line_with_provenance(file, line_start, line);
                self.output.push_str(&expanded.text);
                if let Some(source) = self.db.span(
                    file,
                    BytePos(line_start + line.len()),
                    BytePos(line_start + line.len()),
                ) {
                    self.source_map.push(SourceMapSegment {
                        generated: self.output.len()..self.output.len() + 1,
                        source,
                        origin: SourceOrigin::Source,
                    });
                }
                self.output.push('\n');
                let generated_end = self.output.len();
                self.line_map.push(LineMapping {
                    generated_line: self.line_map.len() + 1,
                    source_file: file,
                    source_line: line_no,
                });
                self.push_format_line(
                    file,
                    line_no,
                    line_start,
                    line_end,
                    line_with_ending,
                    FormatLineKind::ActiveSource,
                    Some(generated_start..generated_end),
                    expanded.chunks,
                );
                debug_assert_eq!(generated_start + expanded.text.len() + 1, self.output.len());
            }
        }
    }

    fn expand_line_with_provenance(
        &mut self,
        file: FileId,
        line_start: usize,
        line: &str,
    ) -> ExpandedLine {
        let mut expanded = ExpandedLine::default();
        let mut source_offset = 0;

        while let Some(relative_start) = line[source_offset..].find("$(") {
            let start = source_offset + relative_start;
            self.push_direct_segment(file, line_start, line, source_offset, start, &mut expanded);

            let Some(relative_end) = line[start + 2..].find(')') else {
                self.push_direct_segment(file, line_start, line, start, line.len(), &mut expanded);
                return expanded;
            };
            let end = start + 2 + relative_end + 1;
            let name = &line[start + 2..end - 1];

            if let Some(binding) = self.defines.get(name).cloned() {
                let replacement = self.expand_macro_text(binding.value.as_str(), 0);
                let generated_start = self.output.len() + expanded.text.len();
                expanded.text.push_str(&replacement);
                let generated_end = self.output.len() + expanded.text.len();

                if let Some(use_span) =
                    self.db
                        .span(file, BytePos(line_start + start), BytePos(line_start + end))
                {
                    let id = self.macro_expansions.push(MacroExpansion {
                        name: name.to_owned(),
                        use_span,
                        replacement,
                        generated_range: generated_start..generated_end,
                        definition: binding.definition,
                        definition_id: binding.definition_id,
                    });
                    self.source_map.push(SourceMapSegment {
                        generated: generated_start..generated_end,
                        source: use_span,
                        origin: SourceOrigin::MacroExpansion(id),
                    });
                    expanded.chunks.push(FormatChunk {
                        source: use_span,
                        text: line[start..end].to_owned(),
                        generated: Some(generated_start..generated_end),
                        kind: FormatChunkKind::MacroUse(id),
                    });
                }
            } else {
                self.push_direct_segment(file, line_start, line, start, end, &mut expanded);
            }

            source_offset = end;
        }

        self.push_direct_segment(
            file,
            line_start,
            line,
            source_offset,
            line.len(),
            &mut expanded,
        );
        expanded
    }

    fn push_direct_segment(
        &mut self,
        file: FileId,
        line_start: usize,
        line: &str,
        start: usize,
        end: usize,
        expanded: &mut ExpandedLine,
    ) {
        if start == end {
            return;
        }

        let generated_start = self.output.len() + expanded.text.len();
        expanded.text.push_str(&line[start..end]);
        let generated_end = self.output.len() + expanded.text.len();

        if let Some(source) =
            self.db
                .span(file, BytePos(line_start + start), BytePos(line_start + end))
        {
            self.source_map.push(SourceMapSegment {
                generated: generated_start..generated_end,
                source,
                origin: SourceOrigin::Source,
            });
            expanded.chunks.push(FormatChunk {
                source,
                text: line[start..end].to_owned(),
                generated: Some(generated_start..generated_end),
                kind: FormatChunkKind::Direct,
            });
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn push_format_line(
        &mut self,
        file: FileId,
        line_no: usize,
        start: usize,
        end: usize,
        text: &str,
        kind: FormatLineKind,
        generated: Option<std::ops::Range<usize>>,
        chunks: Vec<FormatChunk>,
    ) {
        if let Some(span) = self.db.span(file, BytePos(start), BytePos(end)) {
            self.format_lines.push(FormatLine {
                file,
                line: line_no,
                span,
                text: text.to_owned(),
                kind,
                generated,
                chunks,
            });
        }
    }

    fn expand_macro_text(&self, text: &str, depth: usize) -> String {
        const MAX_MACRO_EXPANSION_DEPTH: usize = 64;

        if depth >= MAX_MACRO_EXPANSION_DEPTH {
            return text.to_owned();
        }

        let mut expanded = String::new();
        let mut source_offset = 0;

        while let Some(relative_start) = text[source_offset..].find("$(") {
            let start = source_offset + relative_start;
            expanded.push_str(&text[source_offset..start]);
            let Some(relative_end) = text[start + 2..].find(')') else {
                expanded.push_str(&text[start..]);
                return expanded;
            };
            let end = start + 2 + relative_end + 1;
            let name = &text[start + 2..end - 1];

            if let Some(binding) = self.defines.get(name) {
                expanded.push_str(&self.expand_macro_text(binding.value.as_str(), depth + 1));
            } else {
                expanded.push_str(&text[start..end]);
            }

            source_offset = end;
        }

        expanded.push_str(&text[source_offset..]);
        expanded
    }

    fn defines_as_values(&self) -> HashMap<String, String> {
        self.defines
            .iter()
            .map(|(name, binding)| (name.clone(), binding.value.clone()))
            .collect()
    }
}

pub(super) enum Directive<'a> {
    Include(&'a str),
    Define(&'a str),
    Undef(&'a str),
    Ifdef(&'a str),
    Ifndef(&'a str),
    If(&'a str),
    Elif(&'a str),
    Else,
    Endif,
}

pub(super) fn parse_directive(line: &str) -> Option<Directive<'_>> {
    let line = line.trim_start().split('#').next().unwrap_or("");

    if !line.starts_with('@') {
        return None;
    }

    if let Some(rest) = line.strip_prefix("@include") {
        Some(Directive::Include(rest.trim().trim_matches('"')))
    } else if let Some(rest) = line.strip_prefix("@define") {
        Some(Directive::Define(rest.trim()))
    } else if let Some(rest) = line.strip_prefix("@undef") {
        Some(Directive::Undef(rest.trim()))
    } else if let Some(rest) = line.strip_prefix("@ifdef") {
        Some(Directive::Ifdef(rest.trim()))
    } else if let Some(rest) = line.strip_prefix("@ifndef") {
        Some(Directive::Ifndef(rest.trim()))
    } else if let Some(rest) = line.strip_prefix("@elif") {
        Some(Directive::Elif(rest.trim()))
    } else if let Some(rest) = line.strip_prefix("@if") {
        Some(Directive::If(rest.trim()))
    } else if line.starts_with("@else") {
        Some(Directive::Else)
    } else if line.starts_with("@endif") {
        Some(Directive::Endif)
    } else {
        None
    }
}

/// Splits a `@define` body into its name and value.
///
/// A valueless `@define NAME` defines the name to the empty string, which is
/// what `@ifdef NAME` tests for. It used to be dropped silently, because there
/// was no whitespace to split on.
pub(super) fn parse_define(rest: &str) -> Option<(&str, &str)> {
    let rest = rest.trim();
    let (name, value) = match rest.split_once([' ', '\t']) {
        Some((name, value)) => (name, value),
        None => (rest, ""),
    };

    let name = name.trim();
    if name.is_empty() || name.starts_with('#') {
        return None;
    }

    Some((
        name,
        value
            .split('#')
            .next()
            .unwrap_or("")
            .trim()
            .trim_matches('"'),
    ))
}

pub(super) fn get_path_from_include(parent: &Path, include: &str) -> PathBuf {
    parent
        .parent()
        .unwrap_or_else(|| Path::new(""))
        .join(include)
}

fn physical_lines(text: &str) -> Vec<PhysicalLine<'_>> {
    let mut lines = Vec::new();
    let mut start = 0;
    let mut line_no = 1;

    for (idx, ch) in text.char_indices() {
        if ch != '\n' {
            continue;
        }

        let end = idx + 1;
        let mut content_end = idx;
        if content_end > start && text.as_bytes()[content_end - 1] == b'\r' {
            content_end -= 1;
        }

        lines.push(PhysicalLine {
            line_no,
            start,
            end,
            text_without_ending: &text[start..content_end],
            text_with_ending: &text[start..end],
        });
        start = end;
        line_no += 1;
    }

    if start < text.len() {
        lines.push(PhysicalLine {
            line_no,
            start,
            end: text.len(),
            text_without_ending: &text[start..],
            text_with_ending: &text[start..],
        });
    }

    lines
}

/// Why a `@if`/`@elif` condition could not be evaluated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct CondError {
    /// Human-readable reason, used as the diagnostic message.
    pub message: String,
}

impl CondError {
    fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

/// Evaluates a `@if`/`@elif` condition.
///
/// The grammar, loosest binding first:
///
/// ```text
/// or      := and ( "||" and )*
/// and     := unary ( "&&" unary )*
/// unary   := "!" unary | primary
/// primary := "(" or ")" | "defined" "(" name ")" | comparison
/// comparison := value ( ("==" | "!=") value )?
/// value   := '"' ... '"' | name
/// ```
///
/// A bare `name` with no comparison tests whether it is defined, and a `name`
/// used as a comparison operand expands to its value.
pub(super) fn eval_expr(expr: &str, defines: &HashMap<String, String>) -> Result<bool, CondError> {
    let mut parser = CondParser {
        rest: expr.trim(),
        defines,
        live: true,
    };
    let value = parser.or()?;
    parser.skip_space();
    if !parser.rest.is_empty() {
        return Err(CondError::new(format!(
            "unexpected trailing input \"{}\"",
            parser.rest
        )));
    }
    Ok(value)
}

struct CondParser<'a> {
    rest: &'a str,
    defines: &'a HashMap<String, String>,
    /// False inside a short-circuited branch: the operand is still parsed, so
    /// that syntax errors surface, but names are not required to be defined.
    live: bool,
}

impl<'a> CondParser<'a> {
    fn skip_space(&mut self) {
        self.rest = self.rest.trim_start();
    }

    /// Consumes `tok` if it is next, after any whitespace.
    fn eat(&mut self, tok: &str) -> bool {
        self.skip_space();
        match self.rest.strip_prefix(tok) {
            Some(remainder) => {
                self.rest = remainder;
                true
            }
            None => false,
        }
    }

    fn or(&mut self) -> Result<bool, CondError> {
        let mut acc = self.and()?;
        while self.eat("||") {
            // Operands are parsed either way so that a malformed one is still
            // reported, but only evaluated when the result is still in doubt:
            // `defined(X) || X == "1"` must not resolve an undefined `X`.
            acc = self.and_maybe(!acc)? || acc;
        }
        Ok(acc)
    }

    fn and(&mut self) -> Result<bool, CondError> {
        let mut acc = self.unary()?;
        while self.eat("&&") {
            acc = self.unary_maybe(acc)? && acc;
        }
        Ok(acc)
    }

    /// `and`, evaluated only if `live`; otherwise parsed and discarded.
    fn and_maybe(&mut self, live: bool) -> Result<bool, CondError> {
        let saved = self.live;
        self.live = self.live && live;
        let out = self.and();
        self.live = saved;
        out
    }

    /// `unary`, evaluated only if `live`; otherwise parsed and discarded.
    fn unary_maybe(&mut self, live: bool) -> Result<bool, CondError> {
        let saved = self.live;
        self.live = self.live && live;
        let out = self.unary();
        self.live = saved;
        out
    }

    fn unary(&mut self) -> Result<bool, CondError> {
        // `!=` starts with `!` but is a comparison operator, not a negation.
        self.skip_space();
        if self.rest.starts_with('!') && !self.rest.starts_with("!=") {
            self.rest = &self.rest[1..];
            return Ok(!self.unary()?);
        }
        self.primary()
    }

    fn primary(&mut self) -> Result<bool, CondError> {
        if self.eat("(") {
            let inner = self.or()?;
            if !self.eat(")") {
                return Err(CondError::new("expected \")\""));
            }
            return Ok(inner);
        }

        if self.eat("defined") {
            // Ghidra accepts a space before the parenthesis.
            if !self.eat("(") {
                return Err(CondError::new("expected \"(\" after \"defined\""));
            }
            let name = self.take_value()?;
            if !self.eat(")") {
                return Err(CondError::new("expected \")\" after \"defined(\""));
            }
            return Ok(self.defines.contains_key(name.trim()));
        }

        let lhs = self.take_value()?;

        let negated = if self.eat("==") {
            false
        } else if self.eat("!=") {
            true
        } else {
            // A bare name tests definedness.
            return Ok(self.defines.contains_key(lhs.trim()));
        };

        let rhs = self.take_value()?;
        let equal = self.resolve(&lhs)? == self.resolve(&rhs)?;
        Ok(equal != negated)
    }

    /// Reads one quoted string or bare name.
    fn take_value(&mut self) -> Result<String, CondError> {
        self.skip_space();

        if let Some(body) = self.rest.strip_prefix('"') {
            let Some(end) = body.find('"') else {
                return Err(CondError::new("unterminated string"));
            };
            self.rest = &body[end + 1..];
            return Ok(format!("\"{}\"", &body[..end]));
        }

        let end = self
            .rest
            .find(|c: char| !(c.is_alphanumeric() || c == '_' || c == '.'))
            .unwrap_or(self.rest.len());
        if end == 0 {
            return Err(CondError::new(format!(
                "expected a name or string, found \"{}\"",
                self.rest
            )));
        }
        let (name, remainder) = self.rest.split_at(end);
        self.rest = remainder;
        Ok(name.to_owned())
    }

    /// A quoted string is its own contents; a bare name expands to its
    /// definition.
    fn resolve(&self, raw: &str) -> Result<String, CondError> {
        if let Some(body) = raw.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
            return Ok(body.to_owned());
        }
        match self.defines.get(raw) {
            Some(value) => Ok(value.clone()),
            // A short-circuited operand never had to be resolvable.
            None if !self.live => Ok(String::new()),
            None => Err(CondError::new(format!("\"{raw}\" is not defined"))),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn defines(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
            .collect()
    }

    fn eval(expr: &str, pairs: &[(&str, &str)]) -> bool {
        eval_expr(expr, &defines(pairs)).unwrap_or_else(|e| panic!("{expr:?}: {}", e.message))
    }

    /// The shape that silently dropped RV64C support: the old evaluator
    /// stripped the leading `(` and trailing `)` of the whole expression, then
    /// split on `||`, producing two unbalanced halves that failed to parse.
    #[test]
    fn parenthesized_operands_around_or() {
        let d = &[("ADDRSIZE", "64")];
        assert!(eval(r#"(ADDRSIZE == "64") || (ADDRSIZE == "128")"#, d));
        assert!(eval(r#"(ADDRSIZE == "128") || (ADDRSIZE == "64")"#, d));
        assert!(!eval(r#"(ADDRSIZE == "32") || (ADDRSIZE == "128")"#, d));

        // Doubly parenthesized, as riscv.table.sinc writes it.
        assert!(eval(r#"((ADDRSIZE == "64") || (ADDRSIZE == "128"))"#, d));
    }

    /// Splitting on `||` before `&&` ignored precedence and parens alike.
    #[test]
    fn precedence_and_grouping() {
        let d = &[("A", "1"), ("B", "1")];
        // `A && B || C` groups as `(A && B) || C`.
        assert!(eval("A && B || MISSING", d));
        assert!(eval("MISSING || A && B", d));
        // Parens override it.
        assert!(!eval("A && (MISSING || MISSING2)", d));
        assert!(eval("(A || MISSING) && B", d));
    }

    #[test]
    fn negation() {
        let d = &[("A", "1")];
        assert!(eval("!MISSING", d));
        assert!(!eval("!A", d));
        assert!(eval("!defined(MISSING)", d));
        assert!(eval(r#"!(A == "2")"#, d));
        // `!=` is a comparison, not a negation of `=`.
        assert!(eval(r#"A != "2""#, d));
        assert!(!eval(r#"A != "1""#, d));
    }

    /// Ghidra accepts whitespace between `defined` and its parenthesis.
    #[test]
    fn defined_with_a_space_before_the_paren() {
        let d = &[("A", "1")];
        assert!(eval("defined(A)", d));
        assert!(eval("defined (A)", d));
        assert!(eval("defined ( A )", d));
        assert!(!eval("defined (MISSING)", d));
    }

    /// A short-circuited operand is parsed but not resolved, so the usual
    /// `defined(X) && X == "..."` guard works on an undefined `X`.
    #[test]
    fn short_circuit_does_not_resolve_the_dead_operand() {
        let d = &[("A", "1")];
        assert!(!eval(r#"defined(MISSING) && MISSING == "1""#, d));
        assert!(eval(r#"defined(A) || MISSING == "1""#, d));
    }

    /// A name with no comparison tests definedness; one used as a comparison
    /// operand expands to its value.
    #[test]
    fn bare_names_and_value_expansion() {
        let d = &[("A", "1"), ("EMPTY", "")];
        assert!(eval("A", d));
        assert!(eval("EMPTY", d));
        assert!(!eval("MISSING", d));
        assert!(eval(r#"A == "1""#, d));
        assert!(eval(r#"EMPTY == """#, d));
    }

    /// Errors are reported rather than silently collapsing to false.
    #[test]
    fn malformed_conditions_are_errors() {
        let d = defines(&[("A", "1")]);
        for expr in ["(A", "A ==", "== A", "A &&", r#"A == "unterminated"#, "A B"] {
            assert!(eval_expr(expr, &d).is_err(), "{expr:?} should not evaluate");
        }
        assert!(eval_expr(r#"MISSING == "1""#, &d).is_err());
    }

    /// `@define NAME` with no value used to be dropped entirely, because there
    /// was no whitespace to split on.
    #[test]
    fn valueless_define_registers_the_name() {
        assert_eq!(parse_define("FOO"), Some(("FOO", "")));
        assert_eq!(parse_define("  FOO  "), Some(("FOO", "")));
        assert_eq!(parse_define("FOO bar"), Some(("FOO", "bar")));
        assert_eq!(parse_define("FOO \"bar\""), Some(("FOO", "bar")));
        assert_eq!(parse_define("FOO # a comment"), Some(("FOO", "")));
        assert_eq!(parse_define(""), None);
    }
}
